version: "2"
services:
  test:
    build: .
    user: user
    working_dir: /usr/src
    volumes:
      - ./bower.json:/usr/src/bower.json
      - ./src:/usr/src/src
      - ./test:/usr/src/test
    command: sh -c "bower install && pulp build --censor-lib && pulp test"
  docs:
    build: .
    user: user
    working_dir: /usr/src
    volumes:
      - ./bower.json:/usr/src/bower.json
      - ./src:/usr/src/src
      - ./test:/usr/src/test
      - ./docs:/usr/src/docs
    command: sh -c "bower install && pulp docs"
  publish:
    build: .
    user: user
    working_dir: /usr/src
    volumes:
      - ./.git:/usr/src/.git
      - ./.gitignore:/usr/src/.gitignore
      - ./bower.json:/usr/src/bower.json
      - ./src:/usr/src/src
      - ./test:/usr/src/test
      - ./docs:/usr/src/docs
      - ./.travis.yml:/usr/src/.travis.yml
      - ./Dockerfile:/usr/src/Dockerfile
      - ./LICENSE:/usr/src/LICENSE
      - ./README.md:/usr/src/README.md
      - ./docker-compose.yml:/usr/src/docker-compose.yml
    command: sh -c "bower install && psc-publish --dry-run"
